// <auto-generated />
using System;
using Houseplants.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Houseplants.Migrations
{
    [DbContext(typeof(HouseplantContext))]
    [Migration("20200803193121_InitialDBCreation")]
    partial class InitialDBCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Houseplants.Models.GalleryHouseplant", b =>
                {
                    b.Property<int>("GalleryHouseplantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("GalleryHouseplantId");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("Houseplants.Models.Houseplant", b =>
                {
                    b.Property<int>("HouseplantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fertigation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GalleryHouseplantId")
                        .HasColumnType("int");

                    b.Property<string>("IrrigationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastPlantDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameLatin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("HouseplantId");

                    b.HasIndex("GalleryHouseplantId");

                    b.ToTable("Houseplants");
                });

            modelBuilder.Entity("Houseplants.Models.Houseplant", b =>
                {
                    b.HasOne("Houseplants.Models.GalleryHouseplant", "Gallery")
                        .WithMany()
                        .HasForeignKey("GalleryHouseplantId");
                });
#pragma warning restore 612, 618
        }
    }
}
